Generate_TestCase_Selenium-Web/Generate_TestCase_Selenium_Web/Areas/TestCase/Controllers/GenerateTestCasesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Generate_TestCase_Selenium_Web.Models.Contexts;
using Generate_TestCase_Selenium_Web.Models.ModelDB;
using Microsoft.AspNetCore.Authorization;
using System.Text;
using System.Threading;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium;
using Microsoft.AspNetCore.Routing;
using Generate_TestCase_Selenium_Web.Models;
using Microsoft.AspNetCore.Identity;
using Generate_TestCase_Selenium_Web.Areas.TestCase.Models;
using System.Data;
using FastMember;
using OfficeOpenXml;
using System.IO;
using Generate_TestCase_Selenium_Web.Models.Constants;
using Generate_TestCase_Selenium_Web.Models.Mail;
using OfficeOpenXml.Style;
using System.Drawing;
using Microsoft.Extensions.Logging;
using Microsoft.AspNetCore.SignalR;
using Coravel.Queuing.Interfaces;
using Quartz;
using Microsoft.AspNetCore.Http;

namespace Generate_TestCase_Selenium_Web.Areas.TestCase.Controllers
{
    [Area("TestCase")]
    [Authorize]
    public class GenerateTestCasesController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ElementDBContext _context;
        private int Id_Url;
        private bool IsSelectedElement=false;
        private List<Test_case> ListTestCase;
        private List<List<Input_testcase>> List_ListInputTestcase;
        private List<string> listSpecialCharacter;
        private string browserRun;
        private readonly IQueue _queue;
        private readonly ILogger<GenerateTestCasesController> _logger;
        private readonly IHubContext<JobProgressHub> _hubContext;
        private int Prerequisite_url = -1;
        private string Prerequisite_testcase = null;
        private List<Element> ListEltSelected = null;
        
        //private ChromeDriver chromedriver;
        [TempData]
        public string StatusMessage { get; set; }

        private enum Actions
        {
            fill,
            click,
            select,
            submit,
            check,
            notcheck
        }
        public GenerateTestCasesController(UserManager<ApplicationUser> userManager, ILogger<GenerateTestCasesController> logger, IQueue queue, IHubContext<JobProgressHub> hubContext)
        {
            _context = new ElementDBContext();
            _userManager = userManager;
            _logger = logger;
            // _scheduler = scheduler;
            _queue = queue;
            _hubContext = hubContext;
            Setup();
        }

        //GET: TestCase/id_url/isload
        [Route("/TestCase/{id_url?}/{isload?}")]
        public async Task<IActionResult> Index(int id_url, bool isload = false)
        {
            ViewData["Message"] = StatusMessage;
            //if(StatusMessage!=null)
            //TempData.Remove(StatusMessage);
            var id = _userManager.GetUserId(User);
            int authen = _context.Element.Include(e => e.id_urlNavigation).ThenInclude(p => p.project_).Where(p => p.id_url == id_url && p.id_urlNavigation.project_.Id_User == id).Count();
            if (authen > 0)
            {
                ViewData["id_url"] = id_url;
                var testcaseDBContext = await _context.Test_case.Include(t => t.id_urlNavigation).Include(p => p.Input_testcase).Include(e => e.Element_test)
                    .Include(a => a.Alert_message).Include(r => r.Redirect_url).Where(p => p.id_url == id_url).OrderBy(p => p.TestType).OrderByDescending(p=>p.ModifiedDate).ToListAsync();
                if (ViewData["Message"] == null)
                {
                    if (!isload)
                    {
                        if (testcaseDBContext.Count() == 0)
                        {
                            ViewData["Message"] = "No test case yet";
                        }
                        else
                      if (testcaseDBContext.Count() > 0)
                        {
                            ViewData["Message"] = String.Format("Success, {0} test case(s) were created", testcaseDBContext.Count());
                        }

                        else
                        {
                            ViewData["Message"] = "Error load data";
                        }
                    }
                    else
                        ViewData["Message"] = null;
                }

                ViewData["LoadingTitle"] = "Running test case. Please wait.";
                return View(testcaseDBContext);
            }

            return NotFound();


        }
        // not use. but not delete
        public async Task<IActionResult> Result(int id_url)
        {
            ViewData["id_url"] = id_url;
            var id = _userManager.GetUserId(User);
            int authen = _context.Element.Include(e => e.id_urlNavigation).ThenInclude(p => p.project_).Where(p => p.id_url == id_url && p.id_urlNavigation.project_.Id_User == id).Count();
            if (authen > 0)
            {
                var testcaseDBContext = await _context.Test_case.Include(t => t.id_urlNavigation).Include(p => p.Input_testcase).Where(p => p.id_url == id_url).ToListAsync();

                //  if (testcaseDBContext.Count() == 0)
                //  {
                //      ViewData["Message"] = "No testcase yet";
                //  }
                //  else
                //if (testcaseDBContext.Count() > 0)
                //  {
                //      ViewData["Message"] = String.Format("Success, {0} test case(s) were fo", testcaseDBContext.Count());
                //  }

                //  else
                //  {
                //      ViewData["Message"] = "Error load data";
                //  }

                ViewData["Pass"] = testcaseDBContext.Where(p => p.result.ToLower().Equals("pass")).Count();
                ViewData["Skip"] = testcaseDBContext.Where(p => p.result.ToLower().Equals("skip")).Count();
                ViewData["Failure"] = testcaseDBContext.Where(p => p.result.ToLower().Equals("failure")).Count();
                return View(testcaseDBContext);
            }
            return NotFound();

        }
        private void Setup()
        {

            listSpecialCharacter = new List<string>();
            listSpecialCharacter.Add("!");
            listSpecialCharacter.Add("#");
            listSpecialCharacter.Add("$");
            listSpecialCharacter.Add("%");
            listSpecialCharacter.Add("&");
            listSpecialCharacter.Add("^");
            listSpecialCharacter.Add("|");
            listSpecialCharacter.Add(@"\");
            listSpecialCharacter.Add("/");
            listSpecialCharacter.Add("=");
            listSpecialCharacter.Add("?");
            listSpecialCharacter.Add(";");
            listSpecialCharacter.Add(">");
            listSpecialCharacter.Add("<");
            listSpecialCharacter.Add("-");
            listSpecialCharacter.Add("*");
            listSpecialCharacter.Add("+");
            listSpecialCharacter.Add("{");
            listSpecialCharacter.Add("}");
            listSpecialCharacter.Add("(");
            listSpecialCharacter.Add(")");

        }

        public async Task<IActionResult> Generate_testcase(int id_url, string returnUrl = null)
        {
            IsSelectedElement = false;
            Id_Url = id_url;
            ListTestCase = new List<Test_case>();
            List_ListInputTestcase = new List<List<Input_testcase>>();
            List<Form_elements> forms = await _context.Form_elements.Where(p => p.id_url == Id_Url).ToListAsync();
            if (forms.Count > 0)
            {
                for (int i = 0; i < forms.Count; i++)
                {
                    var _context1 = new ElementDBContext();
                    List<Element> submit = await _context1.Element.Where(p => p.id_url == Id_Url && p.id_form == forms[i].id_form && p.type == "submit").ToListAsync();
                    for (int j = 0; j < submit.Count; j++)
                    {

                        await NotFill_ClickSubmit(forms[i].id_form, j, submit[j]);
                        await Input_Type_Email(forms[i].id_form, j, submit[j]);
                        await Input_Type_Text(forms[i].id_form, j, submit[j]);
                        await ClickAll_TypeRadio(forms[i].id_form, j, submit[j]);
                        await SelectAllElement_TypeSelect(forms[i].id_form, j, submit[j]);
                        await SkipOneSelect_TypeSelect(forms[i].id_form, j, submit[j]);
                        await ClickAll_TypeRadio(forms[i].id_form, j, submit[j]);
                        await Input_Type_Password(forms[i].id_form, j, submit[j]);
                        await Click_Any_CheckBox_TypeCheckBox(forms[i].id_form, j, submit[j]);
                        await ClickAll_TypeCheckBox(forms[i].id_form, j, submit[j]);
                        await Input_Type_TypeDate(forms[i].id_form, j, submit[j]);
                        await Input_Type_TypeNumber(forms[i].id_form, j, submit[j]);
                        await Fill_Form(forms[i].id_form, j, submit[j]);
                    }
                }
                //Xét các trường hợp element không có form
                List<Element> notform = await _context.Element.Where(p => p.id_url == Id_Url && p.id_form ==null).ToListAsync();
                if(notform.Count>0)
                {
                    var _context2 = new ElementDBContext();
                    List<Element> submit = await _context2.Element.Where(p => p.id_url == Id_Url && p.id_form == null && p.type == "submit").ToListAsync();
                    for (int j = 0; j < submit.Count; j++)
                    {

                        await NotFill_ClickSubmit(null, j, submit[j]);
                        await Input_Type_Email(null, j, submit[j]);

Generate_TestCase_Selenium-Web/Generate_TestCase_Selenium_Web/Areas/TestCase/Views/GenerateTestCases/ChaneOptionRadio.cshtml
@model IEnumerable<Generate_TestCase_Selenium_Web.Models.ModelDB.Element>

@{
    ViewData["Title"] = "ChaneOptionRadio";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    ul.breadcrumb {
        padding: 10px 16px;
        list-style: none;
        background-color: #eee;
    }

        ul.breadcrumb li {
            display: inline;
            font-size: 18px;
        }

            ul.breadcrumb li + li:before {
                padding: 8px;
                color: black;
                content: "/\00a0";
            }

            ul.breadcrumb li a {
                color: #0275d8;
                text-decoration: none;
            }

                ul.breadcrumb li a:hover {
                    color: #01447e;
                    text-decoration: underline;
                }
</style>
<h1>Change Option Radio Elemnet</h1>
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item"><a asp-area="TestCase" asp-controller="GenerateTestCases" asp-action="TestData" asp-route-id_url="@ViewBag.id_url" asp-route-id_testcase="@ViewBag.id_testcase">Test data</a></li>
    <li class="breadcrumb-item active">Radio element</li>
</ol>
<partial name="~/Views/Shared/_StatusMessage.cshtml" model="@ViewBag.Message" />
<hr />
<div class="card mb-4">
    <div class="card-header">

        <div class="row">
            <div class="col-6">
                <i class="fas fa-table mr-1"></i>Option Radio Element
            </div>
            <div class="col-6">
                <div class="container">
                    <div class="text-right">

                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="card-body">
        @using (Html.BeginForm("SaveValueOption", "GenerateTestCases", FormMethod.Post, htmlAttributes: new { enctype = "multipart/form-data", @class = "dropzone dropzone-custom needsclick add-professors dz-clickable", @id = "valueoptionform", @novalidate = "novalidate", @name = "valueoptionform" }))
        {
            <input id="id_url" name="id_url" value="@ViewBag.id_url" hidden readonly />
            <input id="id_testcase" name="id_testcase" value="@ViewBag.id_testcase" hidden readonly />
            <input id="id_element" name="id_element" value="@ViewBag.id_element" hidden readonly />
            <div class="table-responsive">
                <table class="table table-condensed table-hover table-bordered" id="inputtable" style="width:100%">
                    <thead>
                        <tr>
                            <th>

                            </th>
                            <th>
                                @Html.DisplayName("Element id")
                            </th>
                            <th>
                                @Html.DisplayName("Name")
                            </th>
                            <th>
                                @Html.DisplayName("Class name")
                            </th>
                            <th>
                                @Html.DisplayName("Type")
                            </th>

                            <th>
                                @Html.DisplayName("Value")
                            </th>

                            <th>
                                @Html.DisplayName("Title")
                            </th>
                            <th>
                                @Html.DisplayName("Form id")
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @{
                                        if (item.id_element == ViewBag.id_element)
                                        {
                                            <input type="radio" name="id_elementchange" id="@item.id_element" value="@item.id_element" checked="checked" />
                                        }
                                        else
                                        {
                                            <input type="radio" name="id_elementchange" id="@item.id_element" value="@item.id_element" />
                                        }
                                    }
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.id_element)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.class_name)
                                </td>
                                @*<td>
                                        @Html.DisplayFor(modelItem => item.tag_name)
                                    </td>*@
                                <td>
                                    @Html.DisplayFor(modelItem => item.type)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.value)
                                </td>
                                <th>
                                    @Html.DisplayFor(modelItem => item.title)
                                </th>
                                <th>
                                    @Html.DisplayFor(modelItem => item.id_form)
                                </th>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        }
    </div>
    <div class="card-footer">
        <div class="text-right">
            <button type="button" class="btn btn-primary" id="submitform" onclick="Submitform()">Save</button>
            <button type="button" class="btn btn-secondary">Cancel</button>
        </div>
    </div>
</div>

<script>


    $(document).ready(function () {
        $('#inputtable').DataTable(
            {
                "lengthMenu": [[10, 20, - 1], [10, 20, "All record"]]
            }
        );
    });
    //$('#modal').on('show.bs.modal', function () {
    //    $(this).find('.modal-body').css({
    //        width: 'auto', //probably not needed
    //        height: 'auto', //probably not needed
    //        'max-height': '100%'
    //    });
    //});
    function Submitform() {

        document.getElementById("valueoptionform").submit();
    };
</script>

Generate_TestCase_Selenium-Web/Generate_TestCase_Selenium_Web/Areas/TestCase/Views/GenerateTestCases/Progress.cshtml
@{
    ViewData["Title"] = "Process";
    Layout = "~/Views/Shared/_LayoutManage.cshtml";
}

<h2>Process is running test case</h2>
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item"><a asp-area="User" asp-controller="Process" asp-action="Index">Progress</a></li>
    <li class="breadcrumb-item active">Progress ID: @ViewBag.JobId</li>
</ol>
<div class="card mb-4">
    <div class="card-header">
        <div class="row">
            <div class="col-5"><i class="fas fa-tasks"></i> @ViewBag.JobId</div>
            <div class="col-7">
                <div class="container">
                    <div class="text-right">
                        <a role="button" class="btn btn-primary" asp-area="User" asp-controller="Results" asp-action="ResultDetail" asp-route-id="@ViewBag.JobId">Result</a>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <div class="card-body">
        <p>
            Status of run test case: <strong>
                @{
                    if (@ViewBag.Message != null)
                    {
                        <span id="job-status">@ViewBag.Message...</span>
                    }
                    else
                    {
                        <span id="job-status">Wating...</span>
                    }
                }

            </strong>
        </p>
    </div>
</div>

@section Scripts
{
    <script src="~/lib/signalr/signalr.js"></script>
    <script>
        document.head || (document.head = document.getElementsByTagName('head')[0]);
        var connection = new signalR.HubConnectionBuilder()
            .withUrl("/jobprogress")
            .configureLogging(signalR.LogLevel.Information)
            .build();

         connection.on("@ViewBag.JobId",
            (message) => {

                document.getElementById("job-status").innerText = message;
                if (message === "Finished!") {
                    alert("Run Finished!");
                }
            });
        connection.start()
            .then(_ => connection.invoke("AssociateJob", "@ViewBag.JobId"))
            .catch(err => console.error(err.toString()));


    </script>
}

Generate_TestCase_Selenium-Web/Generate_TestCase_Selenium_Web/Areas/TestCase/Views/GenerateTestCases/Result.cshtml
@model IEnumerable<Generate_TestCase_Selenium_Web.Models.ModelDB.Test_case>

@{
    ViewData["Title"] = "Result";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="https://cdn.datatables.net/1.10.20/css/jquery.dataTables.min.css" />

<h1>Result</h1>
<hr />

<div class="container">
    <div class="text-left">
        <a class="btn btn-primary" asp-action="Index" asp-controller="GenerateTestCases" asp-route-id_url="@ViewBag.id_url" asp-route-isload="true" role="button">Back to list test case</a>
        <button type="button" class="btn btn-success" name="submit_id" id="btn_id" onclick="Export()">Export</button>
    </div>
</div>
<br />
<partial name="~/Views/Shared/_StatusMessage.cshtml" model="@ViewBag.Message" />


<div class="row">
    <div class="col-md-2">

    </div>
    <div class="col-md-8">
        <div class="row">
            <div class="col-4"><p style="color:green">Pass: @ViewBag.Pass</p></div>
            <div class="col-4"><p style="color:red">Failure: @ViewBag.Failure</p></div>
            <div class="col-4"><p style="color:blue">Skip: @ViewBag.Skip</p></div>
        </div>
    </div>
    <div class="col-md-2">

    </div>
</div>
@using (Html.BeginForm("DownloadExcel", "GenerateTestCases", FormMethod.Post, htmlAttributes: new { enctype = "multipart/form-data", @class = "dropzone dropzone-custom needsclick add-professors dz-clickable", @id = "testcaseform", @novalidate = "novalidate", @name = "testcaseform", @id_url = ViewBag.id_url }))
{
<div class="table-responsive">
    <input id="id_url" name="id_url" value="@ViewBag.id_url" hidden readonly />
    <table id="testcasetable" class="table table-striped table-condensed table-hover table-bordered">
        <thead>
            <tr>
                <th></th>
                <th>
                    @Html.DisplayName("Id test case")
                </th>
                <th>
                    @Html.DisplayName("Description")
                </th>
                <th>
                    @Html.DisplayName("Result")
                </th>
                @*<th>
                        @Html.DisplayNameFor(model => model.is_test)
                    </th>*@
                @*<th>
                        @Html.DisplayName("CreatedDate")
                    </th>*@
                <th>
                    @Html.DisplayName("ModifiedDate")
                </th>
                @*<th>
                        @Html.DisplayNameFor(model => model.id_urlNavigation)
                    </th>*@
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        <input type="checkbox" name="list_Idtestcase" id="list_Idtestcase" value="@item.id_testcase" checked />
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.id_testcase)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.description)
                    </td>

                    @if (item.result.Equals("Pass"))
                    {
                        <td style="color:green">
                            @Html.DisplayFor(modelItem => item.result)
                        </td>
                    }
                    else if (item.result.Equals("Skip"))
                    {
                        <td style="color:blue">
                            @Html.DisplayFor(modelItem => item.result)
                        </td>
                    }
                    else
                    {
                        <td style="color:red">
                            @Html.DisplayFor(modelItem => item.result)
                        </td>
                    }

                    @*<td>
                            @Html.DisplayFor(modelItem => item.is_test)
                        </td>*@
                    @*<td>
                            @Html.DisplayFor(modelItem => item.CreatedDate)
                        </td>*@
                    <td>
                        @Html.DisplayFor(modelItem => item.ModifiedDate)
                    </td>
                    @*<td>
                            @Html.DisplayFor(modelItem => item.id_urlNavigation.name)
                        </td>*@
                    <td>

                        @*@Html.ActionLink("Details", "Details", new { /* id=item.PrimaryKey */ })*@
                        <a class="btn btn-success" asp-action="TestData" asp-controller="GenerateTestCases" asp-route-id_url="@item.id_url" asp-route-id_testcase="@item.id_testcase" role="button">Test data</a>
                        <a class="btn btn-primary" asp-action="TestElement" asp-controller="GenerateTestCases" asp-route-id_url="@item.id_url" asp-route-id_testcase="@item.id_testcase" role="button">Test elements</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>
}
    <script>


        $(document).ready(function () {
            $('#testcasetable').DataTable(
                {
                    "lengthMenu": [[10, 25, 50, - 1], [10, 25, 50, "All record"]],

                }
            );
        });
        
        function Export() {
                document.getElementById("testcaseform").submit();
    };
    </script>