Generate_TestCase_Selenium-Web/Generate_TestCase_Selenium_Web/Models/ModelDB/Test_schedule.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Generate_TestCase_Selenium_Web.Models.ModelDB
{
    public partial class Test_schedule
    {
        public Test_schedule()
        {
            Running_process = new HashSet<Running_process>();
            Testcase_scheduled = new HashSet<Testcase_scheduled>();
        }

        [Key]
        [StringLength(100)]
        public string id_schedule { get; set; }
        [Required]
        [StringLength(450)]
        public string id_user { get; set; }
        [Required]
        [StringLength(10)]
        public string status { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }
        [StringLength(100)]
        public string job_repeat_time { get; set; }

        [InverseProperty("id_scheduleNavigation")]
        public virtual ICollection<Running_process> Running_process { get; set; }
        [InverseProperty("id_scheduleNavigation")]
        public virtual ICollection<Testcase_scheduled> Testcase_scheduled { get; set; }
    }
}

Generate_TestCase_Selenium-Web/Generate_TestCase_Selenium_Web/Areas/User/Controllers/TestScheduleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Generate_TestCase_Selenium_Web.Jobs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Quartz;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Generate_TestCase_Selenium_Web.Models.Contexts;
using Generate_TestCase_Selenium_Web.Models.ModelDB;
using Generate_TestCase_Selenium_Web.Models;
using Microsoft.AspNetCore.Identity;
namespace Generate_TestCase_Selenium_Web.Areas.User.Controllers
{
    [Area("User")]
    [Authorize]
    public class TestScheduleController : Controller
    {
        IScheduler _scheduler;
        private readonly ElementDBContext _context;
        private readonly UserManager<ApplicationUser> _userManager;
        [TempData]
        public string StatusMessage { get; set; }
        public TestScheduleController(IScheduler scheduler, UserManager<ApplicationUser> userManager)
        {
            _scheduler = scheduler;
            _context = new ElementDBContext();
            _userManager = userManager;
        }
        [Route("/Schedule/")]
        public async Task<IActionResult> Index()
        {
            var id_user = _userManager.GetUserId(User);
            var listSchedule = _context.Test_schedule.Where(s => s.id_user == id_user && s.status!="delete");
            ViewData["Message"] = StatusMessage;
            if(StatusMessage!=null)
            TempData.Remove(StatusMessage);
            return View(await listSchedule.ToListAsync());
        }

        public async Task<IActionResult> Create_schedule(string time, string timem, List<string> list_Idtestcase, int id_url)
        {
            Test_schedule test_Schedule = new Test_schedule();
            test_Schedule.CreatedDate = DateTime.Now;
            string scheduleId = Guid.NewGuid().ToString("N");
            test_Schedule.id_schedule = scheduleId;
            var id_user = _userManager.GetUserId(User);
            test_Schedule.id_user = id_user;
            test_Schedule.job_repeat_time = time+":"+timem;
            test_Schedule.status = "running";
            _context.Test_schedule.Add(test_Schedule);
            await _context.SaveChangesAsync();
            foreach (var id in list_Idtestcase)
            {
                Testcase_scheduled testcase_Scheduled = new Testcase_scheduled();
                testcase_Scheduled.id_schedule = scheduleId;
                testcase_Scheduled.id_url = id_url;
                testcase_Scheduled.id_testcase = id;

                _context.Testcase_scheduled.Add(testcase_Scheduled);
            }
            _context.SaveChanges();
            IJobDetail job = JobBuilder.Create<RunTestcaseJob>()
                                         .UsingJobData("scheduleid", scheduleId)
                                         .WithIdentity(scheduleId, id_user)
                                         .StoreDurably()
                                         .RequestRecovery()
                                         .Build();

            await _scheduler.AddJob(job, true);

            ITrigger trigger = TriggerBuilder.Create()
                                             .ForJob(job)
                                             //.UsingJobData("triggerparam", "Simple trigger 1 Parameter")
                                             .WithIdentity(scheduleId + "trigger", id_user)
                                               .WithSchedule(CronScheduleBuilder.DailyAtHourAndMinute(int.Parse(time), int.Parse(timem)))
            //                                 .StartNow()
            //                                 .WithSimpleSchedule(z => z.WithIntervalInSeconds(600).RepeatForever())
                                             .Build();


            await _scheduler.ScheduleJob(trigger);
            StatusMessage = "Create schedule successfully";
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> Stop_schedule(string scheduleId)
        {
            var id_user = _userManager.GetUserId(User);
            await _scheduler.DeleteJob(new JobKey(scheduleId, id_user));
            TriggerKey triggerKey = new TriggerKey("trigger" + scheduleId, id_user);
            await _scheduler.UnscheduleJob(triggerKey);
            var schedule = _context.Test_schedule.Find(scheduleId);
            schedule.status = "stop";
            await _context.SaveChangesAsync();
            StatusMessage = "Stop schedule successfully";
            return RedirectToAction("Index");
        }
       
        public async Task<IActionResult> Delete_schedule(string scheduleId)
        {
            var id_user = _userManager.GetUserId(User);
            await _scheduler.DeleteJob(new JobKey(scheduleId, id_user));
            TriggerKey triggerKey = new TriggerKey("trigger" + scheduleId, id_user);
            await _scheduler.UnscheduleJob(triggerKey);
            var schedule = _context.Test_schedule.Find(scheduleId);
            schedule.status = "delete";
            await _context.SaveChangesAsync();
            StatusMessage = "Delete schedule successfully";
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> Start_schedule(string scheduleId)
        {
            var id_user = _userManager.GetUserId(User);
            Test_schedule test_Schedule = _context.Test_schedule.Find(scheduleId);
            test_Schedule.status = "running";
            _context.Test_schedule.Update(test_Schedule);
            await _context.SaveChangesAsync();
            IJobDetail job = JobBuilder.Create<RunTestcaseJob>()
                                          .UsingJobData("scheduleid", scheduleId)
                                          .WithIdentity(scheduleId, id_user)
                                          .StoreDurably()
                                          .RequestRecovery()
                                          .Build();

            await _scheduler.AddJob(job, true);

            ITrigger trigger = TriggerBuilder.Create()
                                             .ForJob(job)
                                             //.UsingJobData("triggerparam", "Simple trigger 1 Parameter")
                                             .WithIdentity(scheduleId + "trigger", id_user)
                                             .StartNow()
                                             .WithSimpleSchedule(z => z.WithIntervalInSeconds(600).RepeatForever())
                                             .Build();


            await _scheduler.ScheduleJob(trigger);
            StatusMessage = "Start schedule successfully";
            return RedirectToAction("Index");
        }
        [Route("/Schedule/Detail")]
        public async Task<IActionResult> DetailSchedule(string scheduleId)
        {
            var listTestcase = await _context.Testcase_scheduled.Include(p => p.id_).ThenInclude(r=>r.id_urlNavigation).ThenInclude(p=>p.project_).Where(p => p.id_schedule == scheduleId).ToListAsync();
            ViewData["scheduleId"] = scheduleId;
            string[] time = _context.Test_schedule.Find(scheduleId).job_repeat_time.Split(':');
            ViewData["TimeSchedule"] = time[0];
            ViewData["TimeSchedulem"] = time[1];
            ViewData["id_url"] = listTestcase.FirstOrDefault().id_url;
            ViewData["Message"] = StatusMessage;
            ViewData["project"] = listTestcase.FirstOrDefault().id_.id_urlNavigation.url1;
            ViewData["site"] = listTestcase.FirstOrDefault().id_.id_urlNavigation.project_.name;
            if (StatusMessage != null)
                TempData.Remove(StatusMessage);
            return View(listTestcase);
        }
        [HttpPost]
        public async Task<IActionResult> DeleteTestcasesSchedule(string scheduleId, List<string> list_Idtestcase)
        {

            var id = _userManager.GetUserId(User);
            var testcase = await _context.Testcase_scheduled.Include(p => p.id_).Where(p => list_Idtestcase.Contains(p.id_testcase) && p.id_schedule == scheduleId).ToListAsync();
            if (testcase == null)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {

                    _context.Testcase_scheduled.RemoveRange(testcase);
                    await _context.SaveChangesAsync();
                    StatusMessage = "Delete successfully";
                }
                catch (DbUpdateConcurrencyException)
                {
                    StatusMessage = "Delete fail";
                    return RedirectToAction(nameof(DetailSchedule), new { scheduleId = scheduleId });
                }
                //return Json(new { Result = "OK", Message = "Success" });
                return RedirectToAction(nameof(DetailSchedule), new { scheduleId = scheduleId });
                //return RedirectToAction(nameof(Index), new { id_url = id_url, isload = true });
            }
            StatusMessage = "Delete fail";
            return RedirectToAction(nameof(DetailSchedule), new { scheduleId = scheduleId });


        }
        [Route("/Schedule/ChooseProject")]
        public async Task<IActionResult> LoadProject()
        {
            var user = await _userManager.GetUserAsync(User);
            var elementDBContext = await _context.Project.Include(p => p.Id_UserNavigation).Where(p => p.Id_User == user.Id).ToListAsync();
            if (StatusMessage == null)
            {
                if (elementDBContext.Count() == 0)
                {
                    ViewData["Message"] = "No projects yet, create a new one";
                }
                else
                if (elementDBContext.Count() > 0)
                {
                    ViewData["Message"] = String.Format("Found {0} projects", elementDBContext.Count());
                }
                else
                {

Generate_TestCase_Selenium-Web/Generate_TestCase_Selenium_Web/Areas/User/Views/TestSchedule/DetailSchedule.cshtml
@model IEnumerable<Generate_TestCase_Selenium_Web.Models.ModelDB.Testcase_scheduled>

@{
    ViewData["Title"] = "Detail Schedule";
    Layout = "~/Views/Shared/_LayoutManage.cshtml";
}

<link rel="stylesheet" href="https://cdn.datatables.net/1.10.21/css/jquery.dataTables.min.css" />
<link rel="stylesheet" href="https://cdn.datatables.net/fixedheader/3.1.7/css/fixedHeader.dataTables.min.css" />
<script src="https://code.jquery.com/jquery-3.5.1.js"></script>
<script src="https://cdn.datatables.net/1.10.21/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/fixedheader/3.1.7/js/dataTables.fixedHeader.min.js"></script>



<h4>Detail Schedule</h4>
<h5>Project: @ViewBag.project</h5>
<h5>Site: @ViewBag.site</h5>
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item"><a asp-area="User" asp-controller="TestSchedule" asp-action="Index">Test schedule</a></li>
    <li class="breadcrumb-item active">Detail</li>
</ol>

<hr />
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Delete test case</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                Are you sure you want to delete these test cases?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-warning " name="delete" id="delete" onclick="submitDelete()">Delete</button>
            </div>
        </div>
    </div>
</div>
<partial name="~/Views/Shared/_StatusMessage.cshtml" model="@ViewBag.Message" />
<div class="card mb-4">
    <div class="card-header">
        <div class="row">
            <div class="col-3"><i class="fas fa-table mr-1"></i>Test cases list</div>
            <div class="col-9">
                <div class="container">
                    <div class="text-right">
                        @*<button type="button" class="btn btn-warning " name="delete" id="delete" onclick="Delete()">Delete</button>*@
                        <button type="button" class="btn btn-warning" data-toggle="modal" data-target="#deleteModal">
                            Delete
                        </button>
                        <a role="button" class="btn btn-primary" name="moretescase" id="moretescase" asp-action="AddMoreTestCase" asp-route-scheduleId="@ViewBag.scheduleId"
                           asp-route-id_url="@ViewBag.id_url">Add more</a>
                    </div>
                </div>
            </div>
        </div>

    </div>
    <div class="card-body">

        @using (Html.BeginForm("ChangeTimeSchedule", "TestSchedule", FormMethod.Post, htmlAttributes: new { enctype = "multipart/form-data", @class = "dropzone dropzone-custom needsclick add-professors dz-clickable", @id = "timeform", @novalidate = "novalidate", @name = "timeform", @id_url = ViewBag.id_url }))
        {

            <div class="row">
                <div class="col-6">
                    <input id="scheduleId" name="scheduleId" value="@ViewBag.scheduleId" hidden readonly />
                    <label for="time">Job repeat time (between 0h and 23h59):</label>
                    <input type="number" id="time" name="time" min="0" max="23" style="text-align: center;" value="@ViewBag.TimeSchedule"><label> h </label><input type="number" id="timem" style="text-align: center;" name="timem" min="0" max="59" value="@ViewBag.TimeSchedulem"><label> m </label><br><br>
                </div>
                <div class="col-2">
                            <button type="submit" class="btn btn-primary">Update</button>
                        </div>
            </div>


        }
        @using (Html.BeginForm("DeleteTestcasesSchedule", "TestSchedule", FormMethod.Post, htmlAttributes: new { enctype = "multipart/form-data", @class = "dropzone dropzone-custom needsclick add-professors dz-clickable", @id = "testcaseform", @novalidate = "novalidate", @name = "testcaseform", @id_url = ViewBag.id_url }))
        {
            <input id="scheduleId" name="scheduleId" value="@ViewBag.scheduleId" hidden readonly />
            <div class="table-responsive">
                <table id="testcasetable" class="table table-striped table-condensed table-hover table-bordered">
                    <thead>
                        <tr>
                            <th><input type="checkbox" id="checkall" /></th>
                            <th>
                                @Html.DisplayName("Test case id")
                            </th>
                            <th>
                                @Html.DisplayName("Url id")
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    <input type="checkbox" name="list_Idtestcase" id="@item.id_testcase" value="@item.id_testcase" />
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.id_.id_testcase)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.id_url)
                                </td>
                                <td>
                                    @{
                                        string detail = "d" + @item.id_testcase.ToString();
                                        <button type="button" class="btn btn-custon-rounded-three btn-success btn-xs" data-toggle="modal" data-target="#@detail">Detail</button>
                                        string description = "des" + @item.id_testcase.ToString();
                                        <!-- Modal -->

                                        <div class="modal fade" id="@detail" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
                                            <div class="center">
                                                <div class="modal-dialog modal-dialog-center" role="document">
                                                    <div class="modal-content">
                                                        @using (Html.BeginForm("UpdateTestcase", "GenerateTestCases", FormMethod.Post, htmlAttributes: new { enctype = "multipart/form-data", @class = "dropzone dropzone-custom needsclick add-professors dz-clickable", @id = detail, @novalidate = "novalidate", @name = "updatetestcase" }))
                                                        {
                                                            @Html.ValidationSummary(true, null, new { @class = "alert alert-block alert-danger fade in" })
                                                            <div class="modal-header">
                                                                <h5 class="modal-title" id="exampleModalLabel">Detail Test case</h5>
                                                                <button type="button" class="close" data-dismiss="modal" aria-label="Đóng">
                                                                    <span aria-hidden="true">&times;</span>
                                                                </button>
                                                            </div>
                                                            <div class="modal-body">
                                                                <input id="id_url" name="id_url" value="@ViewBag.id_url" hidden readonly />
                                                                <div class="row form-group">
                                                                    <div class="col col-md-3">@Html.Label("Id testcase")</div>
                                                                    <div class="col-12 col-md-9">
                                                                        <input type="text" name="id_testcase" class="input-md form-control" value="@item.id_.id_testcase" readonly>
                                                                    </div>
                                                                </div>
                                                                <div class="row form-group">
                                                                    <div class="col col-md-3">@Html.Label("Description")</div>
                                                                    <div class="col-12 col-md-9">
                                                                        <input type="text" name="description" id="@description" class="input-md form-control" value="@item.id_.description" readonly />

                                                                    </div>
                                                                </div>
                                                                <div class="row form-group">
                                                                    <div class="col col-md-3">@Html.Label("CreatedDate")</div>
                                                                    <div class="col-12 col-md-9">
                                                                        <input type="text" name="CreatedDate" class="input-md form-control" value="@item.id_.CreatedDate" readonly />
                                                                    </div>
                                                                </div>
                                                                <div class="row form-group">
                                                                    <div class="col col-md-3">@Html.Label("ModifiedDate")</div>
                                                                    <div class="col-12 col-md-9">
                                                                        <input type="text" name="ModifiedDate" class="input-md form-control" value="@item.id_.ModifiedDate" readonly />
                                                                    </div>
                                                                </div>


                                                            </div>
                                                            <div class="modal-footer">


                                                                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                                            </div>

                                                        }
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    }
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

            </div>
        }
    </div>
</div>

<script type="text/javascript">


    $(document).ready(function () {
        var table = $('#testcasetable').DataTable(
            {
                "lengthMenu": [[10, 25, 50, - 1], [10, 25, 50, "All record"]],
                "scrollY": "500px",
                "scrollCollapse": true,
                "paging": false,
                "searching": false,

            }
        );

    });
    function submitDelete() {
        if (document.getElementsByName("list_Idtestcase").length <= 0) {
            alert("No test case have been selected");
        }
        else {


            document.getElementById("testcaseform").submit();
        }
    };


    $(function () {
        $("#checkall").click(function () {
            $("input[name='list_Idtestcase']").prop("checked", this.checked);

            $("input[name='list_Idtestcase']").click(function () {
                if ($("input[name='list_Idtestcase']").length == $("input[name='list_Idtestcase']:checked").length) {
                    $("#checkall").prop("checked", "checked");
                }
                else {
                    $("#checkall").prop("checked", false);
                }
            });

        });

    });


</script>

Generate_TestCase_Selenium-Web/Generate_TestCase_Selenium_Web/Areas/User/Views/TestSchedule/LoadProject.cshtml
@model IEnumerable<Generate_TestCase_Selenium_Web.Models.ModelDB.Project>

@{
    ViewData["Title"] = "Project";
    Layout = "~/Views/Shared/_LayoutManage.cshtml";
}

<h1>Choose Project</h1>

<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item active">Project</li>
</ol>

<hr />


<partial name="~/Views/Shared/_StatusMessage.cshtml" model="@ViewBag.Message" />
<div class="card mb-4">
    <div class="card-header">

        <div class="row">
            <div class="col-2">
                <i class="fas fa-table mr-1"></i>Projects list
            </div>
            <div class="col-10">
                <div class="container">
                    <div class="text-right">
                      
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-striped table-condensed table-hover table-bordered" id="exam">
                <thead>
                    <tr>
                        <th style='width: 30%;'>
                            @Html.DisplayName("Project Name")
                        </th>
                        <th style='width: 45%;'>
                            @Html.DisplayName("Description")
                        </th>
                        <th style='width: 10%;'>
                            @Html.DisplayName("Created Date")
                        </th>
                        <th style='width: 10%;'>
                            @Html.DisplayName("Modified Date")
                        </th>

                        <th style='width: 5%;'>@Html.DisplayName("Url list")</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.description)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CreatedDate.Date)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ModifiedDate.Date)
                            </td>

                            <td>
                                <a asp-action="LoadUrl" asp-route-project_id="@item.id" role="button" class="btn btn-primary">Choose</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>
<script>

        
        $(document).ready(function () {
            $('#exam').DataTable(
                {
                    "lengthMenu": [[10, 25, 50, - 1], [10, 25, 50, "All record"]],
                    "ordering": false,


                }
            );
        });
</script>

Generate_TestCase_Selenium-Web/Generate_TestCase_Selenium_Web/Areas/User/Views/TestSchedule/LoadUrl.cshtml
@model IEnumerable<Generate_TestCase_Selenium_Web.Models.ModelDB.Url>

@{
    ViewData["Title"] = "Choose Url";
    Layout = "~/Views/Shared/_LayoutManage.cshtml";
}

<h1>Choose Url</h1>
<h2>Urls of project: @ViewBag.project_name</h2>
<ol class="breadcrumb mb-4">
    <li class="breadcrumb-item"><a asp-area="TestCase" asp-controller="Manage" asp-action="Projects">Project</a></li>
    <li class="breadcrumb-item active">Url</li>
</ol>

<partial name="~/Views/Shared/LoadingViewPartial.cshtml" model="@ViewBag.LoadingTitle" />

<hr />


<partial name="~/Views/Shared/_StatusMessage.cshtml" model="@ViewBag.Message" />
<div class="card mb-4">
    <div class="card-header">

        <div class="row">
            <div class="col-2">
                <i class="fas fa-table mr-1"></i>Urls list
            </div>
            <div class="col-10">
                <div class="container">
                    <div class="text-right">
                       
                    </div>
                </div>
            </div>
        </div>

    </div>
    <div class="card-body">
        <div class="table-responsive">
            <table class="table table-striped table-condensed table-hover table-bordered" id="exam">
                <thead>
                    <tr>
                        <th>
                            @Html.DisplayName("Id")
                        </th>
                        <th>
                            @Html.DisplayName("Name")
                        </th>
                        <th>
                            @Html.DisplayName("url")
                        </th>
                        <th>
                            @Html.DisplayName("Created Date")
                        </th>
                        <th>
                            @Html.DisplayName("Modified Date")
                        </th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.id_url)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.name)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.url1)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.CreatedDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.ModifiedDate)
                            </td>

                            <td>
                                        <a role="button" class="btn btn-primary" asp-area="User" asp-controller="TestSchedule" asp-action="LoadTestase" asp-route-id_url="@item.id_url">Choose</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>
</div>

<script>

   
    $(document).ready(function () {
        $('#exam').DataTable(
            {
                "lengthMenu": [[4, 10, 25, 50, - 1], [4, 10, 25, 50, "All record"]],
                "ordering": false,


            }
        );
    });
</script>